In [ ]:
pip install pgmpy

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 7.2 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinu

In [ ]:
import numpy as np
import gym

In [ ]:
env = gym.make("FrozenLake-v1")
n_observations = env.observation_space.n
n_actions = env.action_space.n

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [ ]:
Q_table = np.zeros((n_observations,n_actions))
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
n_episodes = 10000

max_iter_episode = 100

exploration_proba = 1

exploration_decreasing_decay = 0.001


min_exploration_proba = 0.01


gamma = 0.99


lr = 0.1

In [ ]:
total_rewards_episode = list()
rewards_per_episode = list();

In [ ]:

for e in range(n_episodes):
    current_state = env.reset()
    done = False

    total_episode_reward = 0

    for i in range(max_iter_episode):


        if np.random.uniform(0,1) < exploration_proba:
            action = env.action_space.sample()
        else:
            action = np.argmax(Q_table[current_state,:])

        next_state, reward, done, _ = env.step(action)

        Q_table[current_state, action] = (1-lr) * Q_table[current_state, action] +lr*(reward + gamma*max(Q_table[next_state,:]))
        total_episode_reward = total_episode_reward + reward
        if done:
            break
        current_state = next_state
    exploration_proba = max(min_exploration_proba, np.exp(-exploration_decreasing_decay*e))
    rewards_per_episode.append(total_episode_reward)

/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:241: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


In [ ]:
print("Mean reward per thousand episodes")
for i in range(10):
    print((i+1)*1000,": mean espiode reward: ",\
          np.mean(rewards_per_episode[1000*i:1000*(i+1)]))

Mean reward per thousand episodes
1000 : mean espiode reward:  0.047
2000 : mean espiode reward:  0.225
3000 : mean espiode reward:  0.408
4000 : mean espiode reward:  0.587
5000 : mean espiode reward:  0.691
6000 : mean espiode reward:  0.642
7000 : mean espiode reward:  0.673
8000 : mean espiode reward:  0.685
9000 : mean espiode reward:  0.67
10000 : mean espiode reward:  0.659


In [ ]:
print(Q_table)

[[0.46845304 0.45778074 0.45566927 0.45979305]
 [0.30896051 0.30124082 0.27050034 0.4124478 ]
 [0.37123446 0.28063131 0.24835767 0.28549051]
 [0.03052351 0.15699102 0.02265706 0.09255616]
 [0.48381613 0.43599122 0.38848981 0.35771406]
 [0.         0.         0.         0.        ]
 [0.29908757 0.10273256 0.13996396 0.09438722]
 [0.         0.         0.         0.        ]
 [0.49227788 0.43951366 0.18852726 0.52776213]
 [0.37278517 0.57930554 0.43403493 0.27189095]
 [0.51988686 0.34048032 0.47800803 0.31948909]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.42556537 0.45778963 0.75398312 0.48673117]
 [0.69674589 0.88768014 0.7128418  0.71887826]
 [0.         0.         0.         0.        ]]
